---
name: "nix-build"
on:
  push:
    branches:
      - '**'
jobs:
  materialize:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
      - name: install nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://cache.nixos.org/
      - name: install cachix
        uses: cachix/cachix-action@v10
        with:
          name: canonical-llc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: set supported systems
        run: echo $(uname -m)-$(uname -s) | tr '[:upper:]' '[:lower:]' | sed -E 's/^(.*)$/[ "\1" ]/' | tee supported-systems.nix
      - name: materialize
        run: nix run .#update-materialized
      - name: commit
        uses: EndBug/add-and-commit@v8
        with:
          add: nix/haskell/plan-sha256 nix/haskell/materialized
          message: materialize
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest] #, macos-latest]
    needs: materialize
    runs-on: ${{matrix.platform}}
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
      - name: install nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://cache.nixos.org/
      - name: install cachix
        uses: cachix/cachix-action@v10
        with:
          name: canonical-llc
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: set supported systems
        run: echo $(uname -m)-$(uname -s) | tr '[:upper:]' '[:lower:]' | sed -E 's/^(.*)$/[ "\1" ]/' | tee supported-systems.nix
      - run: nix flake check --print-build-logs
      - run: nix develop --print-build-logs  --command echo Ready
